"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getTrimmedSurname = exports.getTrimmedName = exports.getRandomPassword = exports.getPlatformId = exports.getPhoneNumber = exports.getNoteTitle = exports.getNoteContent = exports.getCustomerNotesByCustomerOldId = exports.getCombinedField = exports.getAllCustomers = void 0;
var getAllCustomers_1 = require("./getAllCustomers");
Object.defineProperty(exports, "getAllCustomers", { enumerable: true, get: function () { return getAllCustomers_1.getAllCustomers; } });
var getCombinedField_1 = require("./getCombinedField");
Object.defineProperty(exports, "getCombinedField", { enumerable: true, get: function () { return getCombinedField_1.getCombinedField; } });
var getCustomerNotesByCustomerOldId_1 = require("./getCustomerNotesByCustomerOldId");
Object.defineProperty(exports, "getCustomerNotesByCustomerOldId", { enumerable: true, get: function () { return getCustomerNotesByCustomerOldId_1.getCustomerNotesByCustomerOldId; } });
// import { getDataSourceId } from "./getDataSourceId";
var getNoteContent_1 = require("./getNoteContent");
Object.defineProperty(exports, "getNoteContent", { enumerable: true, get: function () { return getNoteContent_1.getNoteContent; } });
var getNoteTitle_1 = require("./getNoteTitle");
Object.defineProperty(exports, "getNoteTitle", { enumerable: true, get: function () { return getNoteTitle_1.getNoteTitle; } });
// import { getNoteUserId } from "./getNoteUserId";
var getPhoneNumber_1 = require("./getPhoneNumber");
Object.defineProperty(exports, "getPhoneNumber", { enumerable: true, get: function () { return getPhoneNumber_1.getPhoneNumber; } });
var getPlatformId_1 = require("./getPlatformId");
Object.defineProperty(exports, "getPlatformId", { enumerable: true, get: function () { return getPlatformId_1.getPlatformId; } });
var getRandomPassword_1 = require("./getRandomPassword");
Object.defineProperty(exports, "getRandomPassword", { enumerable: true, get: function () { return getRandomPassword_1.getRandomPassword; } });
// import { getTagIds } from "./getTagIds";
var getTrimmedName_1 = require("./getTrimmedName");
Object.defineProperty(exports, "getTrimmedName", { enumerable: true, get: function () { return getTrimmedName_1.getTrimmedName; } });
var getTrimmedSurname_1 = require("./getTrimmedSurname");
Object.defineProperty(exports, "getTrimmedSurname", { enumerable: true, get: function () { return getTrimmedSurname_1.getTrimmedSurname; } });
